//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>General</summary>
	[PublishedModel("general")]
	public partial class General : WebsiteSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "general";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<General, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public General(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Email: Primary email contact for customers
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("companyEmail")]
		public string CompanyEmail => this.Value<string>("companyEmail");

		///<summary>
		/// Latitude
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("companyLatitude")]
		public string CompanyLatitude => this.Value<string>("companyLatitude");

		///<summary>
		/// Company Logo: The image must be in .jpg, .png, or. gif format. Minimum 112x112px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("companyLogo")]
		public IPublishedContent CompanyLogo => this.Value<IPublishedContent>("companyLogo");

		///<summary>
		/// Longitude
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("companyLongitude")]
		public string CompanyLongitude => this.Value<string>("companyLongitude");

		///<summary>
		/// Company Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("companyName")]
		public string CompanyName => this.Value<string>("companyName");

		///<summary>
		/// Phone Number: A business phone number meant to be the primary contact method for customers. Be sure to include the country code and area code in the phone number.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("companyPhoneNumber")]
		public string CompanyPhoneNumber => this.Value<string>("companyPhoneNumber");

		///<summary>
		/// Contact Form Email: Email that contact form sends to.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactFormEmail")]
		public string ContactFormEmail => this.Value<string>("contactFormEmail");

		///<summary>
		/// Learn More Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cookieDialogLearnMoreLink")]
		public Umbraco.Web.Models.Link CookieDialogLearnMoreLink => this.Value<Umbraco.Web.Models.Link>("cookieDialogLearnMoreLink");

		///<summary>
		/// Postion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cookieDialogPostion")]
		public string CookieDialogPostion => this.Value<string>("cookieDialogPostion");

		///<summary>
		/// Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cookieDialogText")]
		public string CookieDialogText => this.Value<string>("cookieDialogText");

		///<summary>
		/// Theme
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("cookieDialogTheme")]
		public string CookieDialogTheme => this.Value<string>("cookieDialogTheme");

		///<summary>
		/// Dismiss Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("dismissButtonText")]
		public string DismissButtonText => this.Value<string>("dismissButtonText");

		///<summary>
		/// Disqus Shortname: To enable comments, add your Disqus shortname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("disqusShortname")]
		public string DisqusShortname => this.Value<string>("disqusShortname");

		///<summary>
		/// Enable Cookie Consent Dialog
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("enableCookieConsentDialog")]
		public bool EnableCookieConsentDialog => this.Value<bool>("enableCookieConsentDialog");

		///<summary>
		/// Google Analytics ID: UA-XXXXX-X
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("googleAnalyticsID")]
		public string GoogleAnalyticsID => this.Value<string>("googleAnalyticsID");

		///<summary>
		/// Google Maps API Key
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("googleMapsAPIKey")]
		public string GoogleMapsApikey => this.Value<string>("googleMapsAPIKey");

		///<summary>
		/// Google Tag Manager ID: GTM-XXXXXXX
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("googleTagManagerID")]
		public string GoogleTagManagerID => this.Value<string>("googleTagManagerID");

		///<summary>
		/// Access Token
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("instagramAccessToken")]
		public string InstagramAccessToken => this.Value<string>("instagramAccessToken");

		///<summary>
		/// User ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("instagramUserID")]
		public string InstagramUserID => this.Value<string>("instagramUserID");

		///<summary>
		/// Username: Your instagram username without @
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("instagramUsername")]
		public string InstagramUsername => this.Value<string>("instagramUsername");

		///<summary>
		/// API Key
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("newsletterAPIKey")]
		public string NewsletterApikey => this.Value<string>("newsletterAPIKey");

		///<summary>
		/// Default Subscriber List ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("newsletterDefaultSubscriberListID")]
		public string NewsletterDefaultSubscriberListID => this.Value<string>("newsletterDefaultSubscriberListID");

		///<summary>
		/// Email Marketing Provider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("newsletterEmailMarketingProvider")]
		public string NewsletterEmailMarketingProvider => this.Value<string>("newsletterEmailMarketingProvider");

		///<summary>
		/// Site Name: Company or website name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("siteName")]
		public string SiteName => this.Value<string>("siteName");

		///<summary>
		/// Title Signature: This text will be added at the end of the title on all pages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("titleSignature")]
		public string TitleSignature => this.Value<string>("titleSignature");

		///<summary>
		/// Twitter Username: Enter twitter username. Include @ in the beginning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("twitterUsername")]
		public string TwitterUsername => this.Value<string>("twitterUsername");
	}
}
