//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Slider</summary>
	[PublishedModel("slider")]
	public partial class Slider : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "slider";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Slider, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Slider(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Autoplay: Set autoplay time in milliseconds (1000 = 1 second) Set to 0 to disable autoplay
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("autoplay")]
		public string Autoplay => this.Value<string>("autoplay");

		///<summary>
		/// Fade Animation: Fades between transitioning slides instead of moving.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("fadeAnimation")]
		public bool FadeAnimation => this.Value<bool>("fadeAnimation");

		///<summary>
		/// Pause Autoplay On Hover: If checked, autoplay will pause when mouse is over the slider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pauseAutoplayOnHover")]
		public bool PauseAutoplayOnHover => this.Value<bool>("pauseAutoplayOnHover");

		///<summary>
		/// Show Next/Prev Arrows: Show next and previous buttons inside the slider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("showNextPrevArrows")]
		public bool ShowNextPrevArrows => this.Value<bool>("showNextPrevArrows");

		///<summary>
		/// Show Page Dots: Show slider dots in the bottom of the slider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("showPageDots")]
		public bool ShowPageDots => this.Value<bool>("showPageDots");

		///<summary>
		/// Widgets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("widgets")]
		public IEnumerable<IPublishedElement> Widgets => this.Value<IEnumerable<IPublishedElement>>("widgets");

		///<summary>
		/// Wrap Around: If checked, slider will go from last slide to first slide
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("wrapAround")]
		public bool WrapAround => this.Value<bool>("wrapAround");
	}
}
